// Mocks generated by Mockito 5.4.6 from annotations
// in moviebrowser/test/presentation/bloc/favorites_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:moviebrowser/core/error/failures.dart' as _i6;
import 'package:moviebrowser/core/usecases/usecase.dart' as _i8;
import 'package:moviebrowser/features/favorites/domain/repositories/favorites_repository.dart'
    as _i2;
import 'package:moviebrowser/features/favorites/domain/usecases/add_favorite.dart'
    as _i9;
import 'package:moviebrowser/features/favorites/domain/usecases/get_favorites.dart'
    as _i4;
import 'package:moviebrowser/features/favorites/domain/usecases/is_favorite.dart'
    as _i11;
import 'package:moviebrowser/features/favorites/domain/usecases/remove_favorite.dart'
    as _i10;
import 'package:moviebrowser/features/movies/domain/entities/movie.dart' as _i7;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFavoritesRepository_0 extends _i1.SmartFake
    implements _i2.FavoritesRepository {
  _FakeFavoritesRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [GetFavorites].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetFavorites extends _i1.Mock implements _i4.GetFavorites {
  MockGetFavorites() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoritesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoritesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FavoritesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>> call(
    _i8.NoParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i7.Movie>>(
                    this,
                    Invocation.method(#call, [params]),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Movie>>>);
}

/// A class which mocks [AddFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockAddFavorite extends _i1.Mock implements _i9.AddFavorite {
  MockAddFavorite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoritesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoritesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FavoritesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
    _i9.AddFavoriteParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [RemoveFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockRemoveFavorite extends _i1.Mock implements _i10.RemoveFavorite {
  MockRemoveFavorite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoritesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoritesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FavoritesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(
    _i10.RemoveFavoriteParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [IsFavorite].
///
/// See the documentation for Mockito's code generation for more information.
class MockIsFavorite extends _i1.Mock implements _i11.IsFavorite {
  MockIsFavorite() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FavoritesRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeFavoritesRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.FavoritesRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, bool>> call(
    _i11.IsFavoriteParams? params,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, bool>>.value(
              _FakeEither_1<_i6.Failure, bool>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, bool>>);
}
