// Mocks generated by Mockito 5.4.6 from annotations
// in moviebrowser/test/domain/usecases/get_popular_movies_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i4;

import 'package:dartz/dartz.dart' as _i2;
import 'package:mockito/mockito.dart' as _i1;
import 'package:moviebrowser/core/error/failures.dart' as _i5;
import 'package:moviebrowser/features/movies/domain/entities/movie.dart' as _i6;
import 'package:moviebrowser/features/movies/domain/repositories/movie_repository.dart'
    as _i3;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeEither_0<L, R> extends _i1.SmartFake implements _i2.Either<L, R> {
  _FakeEither_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [MovieRepository].
///
/// See the documentation for Mockito's code generation for more information.
class MockMovieRepository extends _i1.Mock implements _i3.MovieRepository {
  MockMovieRepository() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getPopularMovies({
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#getPopularMovies, [], {#page: page}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
                    this,
                    Invocation.method(#getPopularMovies, [], {#page: page}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> searchMovies(
    String? query, {
    int? page = 1,
  }) =>
      (super.noSuchMethod(
            Invocation.method(#searchMovies, [query], {#page: page}),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
                    this,
                    Invocation.method(#searchMovies, [query], {#page: page}),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, _i6.Movie>> getMovieDetails(
    int? movieId,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieDetails, [movieId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, _i6.Movie>>.value(
              _FakeEither_0<_i5.Failure, _i6.Movie>(
                this,
                Invocation.method(#getMovieDetails, [movieId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, _i6.Movie>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, String?>> getMovieVideoKey(int? movieId) =>
      (super.noSuchMethod(
            Invocation.method(#getMovieVideoKey, [movieId]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, String?>>.value(
              _FakeEither_0<_i5.Failure, String?>(
                this,
                Invocation.method(#getMovieVideoKey, [movieId]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, String?>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>> getCachedMovies() =>
      (super.noSuchMethod(
            Invocation.method(#getCachedMovies, []),
            returnValue:
                _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>.value(
                  _FakeEither_0<_i5.Failure, List<_i6.Movie>>(
                    this,
                    Invocation.method(#getCachedMovies, []),
                  ),
                ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, List<_i6.Movie>>>);

  @override
  _i4.Future<_i2.Either<_i5.Failure, void>> cacheMovies(
    List<_i6.Movie>? movies,
  ) =>
      (super.noSuchMethod(
            Invocation.method(#cacheMovies, [movies]),
            returnValue: _i4.Future<_i2.Either<_i5.Failure, void>>.value(
              _FakeEither_0<_i5.Failure, void>(
                this,
                Invocation.method(#cacheMovies, [movies]),
              ),
            ),
          )
          as _i4.Future<_i2.Either<_i5.Failure, void>>);
}
